### PR TITLE
Basic tests for answerQuestion method of FormEntryController

### PR DESCRIPTION
**Pull request by phillipm**
This PR is a basic test for answering simple questions with and without constraints.

FormEntryController.answerQuestion has some strange logic in it that has to do with answering questions that are complex. For background complex questions have copy tags in them that need xml subtree substitution to occur during evaluation.

I wanted to test that logic, gave up after not being able to produce a valid xform as input.

### CODE REVIEW

**Comment by millerdev** [comment]
Tests! Sweet!

**Comment by snopoke** [comment]
:star2:

**Comment by ctsims** [comment]
@phillipm Are these ready for merging? Don't see the flag, but look good to me.

**Comment by phillipm** [comment]
@ctsims yup, I created this PR before knowing about labels. Should be ready to review/merge.

**Pull request merged**
