### PR TITLE
Remove title println

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @ctsims

### CODE REVIEW

**Comment by czue** [comment]
:eyes:

**Comment by ctsims** [comment]
@benrudolph @wpride 

! Not 100% sure about this. this println is _super_ _super_ helpful during debugging to see what xform was being parsed when a parse exception throws,

**Comment by benrudolph** [comment]
Is it possible to include the title in the exception then? I don't like the println cause we have no control over the log level and the format is useless in terms of trying to figure out the timestamp

**Comment by wpride** [comment]
@ctsims my thinking was that I've always never used this sysout in debugging - I think I usually use the exception as ben suggests. If there're situations where this doesn't work or you rely on it happy to add it back in of course (though I'm definitely feeling rudolph's pain with the touchforms logs lately (which we shouldn't be completely beholden to))

**Comment by ctsims** [comment]
Hey: If we can include it in traces or something that works. The thing is
that the place this is really helpful is during debugging with j2me apps
which is already incredibly painful, so I'd really _really_ like to not
lose this tool.

shouldn't touchforms be dropping stdout anyway? I'd think we'd only want to
log stderr?

**Pull request merged**
