### PR TITLE
Building core tests without j2me

### PR DESCRIPTION
**Pull request by phillipm**
unit tests can now be built/run from core build file via 'ant test'

### CODE REVIEW

**Comment by millerdev** [comment]
Not that I ever review Java code at this point, but it would be much easier for the reviewer if you split out the style commits into a separate PR.

**Comment by phillipm** [comment]
Cheers, I'll be sure to do that next time.
Also worth mentioning, I mistakenly created this branch from pull request #47, so those commits (all but the last 5) are present in this PR too.

**Comment by millerdev** [comment]
Hey, that's understandable. And sorry if my comment was a bit terse. I applaud anyone who takes the time to do code cleanup. Nice work!

**Comment by wpride** [comment]
Daniel is a notorious hardo

**Pull request closed without merging**
